name: 'Slack Notify PR'
description: 'Post PR notifications to Slack.'
inputs:
  webhook-url:
    description: 'Webhook URL for Your Workspace'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
